"""S07–S12 of the reviewed analysis catalog."""

from __future__ import annotations

from typing import Any

from .catalog_lib import A, G, P, decomp, item  # constructors only; no import of seed.py


def _add(
    analyses: list,
    decomps: list,
    sh_id: str,
    values: list[str],
    goals: list,
    items_spec: list,
) -> None:
    items = []
    for lid, gid, loss, rid, req, note, asms, specs in items_spec:
        items.append(item(lid, gid, loss, rid, req, note))
        decomps.append(decomp(rid, sh_id, gid, loss, req, asms, specs))
    analyses.append({"stakeholder_id": sh_id, "values": values, "goals": goals, "items": items})


def analyses_part2() -> list[dict[str, Any]]:
    a, d = [], []
    _fill(a, d)
    return a


def decomps_part2() -> list[dict[str, Any]]:
    a, d = [], []
    _fill(a, d)
    return d


def _fill(analyses: list, decomps: list) -> None:
    _add(
        analyses, decomps, "S07",
        ["model IP", "reputational accuracy", "limited downstream liability"],
        [G("G-S07-1", "Deliver a usable person-recognition stack without absorbing the manufacturer's product risk"),
         G("G-S07-2", "Keep training data and weights from leaking via on-device deployment")],
        [
            ("L-S07-1", "G-S07-2",
             "On-device weights are extracted from a consumer dashcam and republished.",
             "R-S07-1",
             "A person who buys a dashcam does not obtain a working copy of the contractor's production model weights.",
             "Offline deployment is explicitly on the table in the scenario.",
             [A("R-S07-1-A1", "Hardware is a secure enclave that owners cannot dump.", "Dashcams are cheap and routinely rooted."),
              A("R-S07-1-A2", "A distilled on-device model has no value if stolen.", "It still encodes the contractor's data."),
              A("R-S07-1-A3", "Matching can stay on the phone, which has a better TEE than the camera.", "Phones are also jailbroken; it also increases data movement.")],
             [P("R-S07-1-P1", "person-recognition model", "Ship an on-device extractor/embedder that is not the full cloud model; keep the gallery comparison key on the coordinator if possible."),
              P("R-S07-1-P2", "dashcam firmware", "Store weights in a locked partition and refuse to export them over USB debug."),
              P("R-S07-1-P3", "person-recognition contractor", "Watermark embeddings so a leaked model can be attributed.")]),
            ("L-S07-2", "G-S07-1",
             "Public audits show large error gaps on children or on darker skin, and the contractor is named.",
             "R-S07-2",
             "Disparities in whether a visible missing child is reported are not systematically associated with the child's age band or skin tone in deployed searches.",
             "This is a world-level fairness requirement, not 'equal F1 on a benchmark'.",
             [A("R-S07-2-A1", "Adult mugshot benchmarks predict child dashcam performance.", "They do not."),
              A("R-S07-2-A2", "Low-light robustness advertised by the contractor covers streetlights and headlights equally across skin tones.", "It often does not."),
              A("R-S07-2-A3", "We can collect child dashcam labels legally.", "Children's data is specially protected.")],
             [P("R-S07-2-P1", "person-recognition model", "Report match_score distributions sliced by age-band and lighting tags on a sealed evaluation set, not only a single AUC."),
              P("R-S07-2-P2", "cloud/search coordinator", "Log (search-id, age-band, lighting-tag, match_score, reviewer-decision) for disparity review, without storing extra identity."),
              P("R-S07-2-P3", "dashcam firmware", "Attach a lighting/quality tag to each crop so slices are possible.")]),
            ("L-S07-3", "G-S07-1",
             "Latency or downtime of a cloud Rekognition-like path misses the useful window.",
             "R-S07-3",
             "A sighting is not lost solely because a cloud inference endpoint was slow or unreachable.",
             "The dashcam is already offline; adding a cloud round-trip stacks two radios.",
             [A("R-S07-3-A1", "On-device or on-phone inference is always available as fallback.", "Low-end SKUs cannot run it."),
              A("R-S07-3-A2", "Cloud batching is fine because searches are rare.", "When a search is on, latency still matters."),
              A("R-S07-3-A3", "The contractor's SLA includes dashcam-like blur and night frames.", "Their SLA may be clean studio images.")],
             [P("R-S07-3-P1", "dashcam firmware", "Run local matching when a search-alert is present; do not block on a cloud round-trip."),
              P("R-S07-3-P2", "phone companion app", "If local matching is incapable, queue crops and retry cloud inference without dropping the GPS/time that makes the report a sighting."),
              P("R-S07-3-P3", "person-recognition contractor", "Expose an offline SDK path, not only a hosted API.")]),
            ("L-S07-4", "G-S07-2",
             "Fine-tuning uses photos the contractor had no license to train on, and a lawsuit lands on both companies.",
             "R-S07-4",
             "A child's photo provided for a live search is not used to train or advertise a model.",
             "Live searches are the most sensitive data the contractor will ever see.",
             [A("R-S07-4-A1", "Default cloud settings do not log production images into a training bucket.", "Many hosted APIs do, unless contracted off."),
              A("R-S07-4-A2", "Fine-tune infrastructure the manufacturer operates is isolated from the vendor's other customers.", "Shared GPUs and datasets are cheaper."),
              A("R-S07-4-A3", "Expired search photos cannot be recovered from experiment trackers.", "Weights-and-biases style tools hoard samples.")],
             [P("R-S07-4-P1", "person-recognition contractor", "API option and default: do not persist request images; return only scores."),
              P("R-S07-4-P2", "cloud/search coordinator", "Manufacturer-operated fine-tune jobs read only a licensed corpus, never the live search-alert store."),
              P("R-S07-4-P3", "cloud/search coordinator", "Block experiment-tracker uploads of search-alert images at the gateway.")]),
            ("L-S07-5", "G-S07-1",
             "The contractor is subpoenaed as the 'face recognition company' for every ChildFind case.",
             "R-S07-5",
             "The contractor does not receive a copy of every production video frame, only what the manufacturer must send to meet a specified inference path.",
             "Data minimization is also liability minimization.",
             [A("R-S07-5-A1", "On-device inference means the vendor never sees production frames.", "Updates and 'helpdesk' uploads will reintroduce them."),
              A("R-S07-5-A2", "A subpoena to the manufacturer is enough for courts.", "Plaintiffs will sue everyone in the chain."),
              A("R-S07-5-A3", "Support logs can be sampled without full video.", "Engineers will ask for the clip.")],
             [P("R-S07-5-P1", "dashcam firmware", "Default inference path keeps frames on-device; cloud path sends crops not full video."),
              P("R-S07-5-P2", "person-recognition contractor", "Support channel accepts quality tags and scores, not raw clips, unless a named incident ticket is opened."),
              P("R-S07-5-P3", "cloud/search coordinator", "Separate the manufacturer case file from any vendor ticket so a vendor subpoena does not automatically include GPS trails.")]),
        ],
    )

    _add(
        analyses, decomps, "S08",
        ["anonymity in public space", "purpose limitation", "no secondary use"],
        [G("G-S08-1", "Move through streets without being biometrically identified by a consumer camera network"),
         G("G-S08-2", "Not have an image from a sensitive place reused later")],
        [
            ("L-S08-1", "G-S08-1",
             "A bystander's face is embedded and kept so they can be re-identified after the search ends.",
             "R-S08-1",
             "A person who is not the subject of an authorized search is not assigned a persistent identity from ChildFind processing.",
             "This is the mass-surveillance requirement hiding inside a child-safety feature.",
             [A("R-S08-1-A1", "We only compare to one search photo, so we are not identifying bystanders.", "Comparison still detects and embeds every face."),
              A("R-S08-1-A2", "Embeddings without names are not identifications.", "They are linkable identifiers."),
              A("R-S08-1-A3", "People in public have no remaining biometric expectation.", "Regulators disagree, especially for children bystanders.")],
             [P("R-S08-1-P1", "dashcam firmware", "Do not store embeddings except the current search photo's embedding and in-memory crops of the current matching window."),
              P("R-S08-1-P2", "person-recognition model", "Output match_score versus the search photo only; do not output a gallery id for non-matches."),
              P("R-S08-1-P3", "dashcam firmware", "Zero in-memory crops when the search-id expires or the vehicle powers down.")]),
            ("L-S08-2", "G-S08-2",
             "A still of a bystander at a clinic, shelter, or protest is later reused in another investigation.",
             "R-S08-2",
             "ChildFind stills are not available to reuse for a purpose other than the originating missing-child search.",
             "Secondary use is how dashcams become police databases.",
             [A("R-S08-2-A1", "Retention limits will be honored by every agency copy.", "Once emailed, they will not."),
              A("R-S08-2-A2", "The original crash-evidence recording is a separate store with its own warrant process.", "Police will ask to 'just look at ChildFind' instead of getting a warrant for the loop."),
              A("R-S08-2-A3", "Edge kiosks do not keep a longer archive than the car.", "Centralizing makes longer retention tempting.")],
             [P("R-S08-2-P1", "cloud/search coordinator", "Bind every still to a search-id and refuse API access with a different purpose token."),
              P("R-S08-2-P2", "cloud/search coordinator", "Do not provide a free-text 'search all historical stills' endpoint."),
              P("R-S08-2-P3", "edge kiosk", "Purge cached clips on the same expiry as the car; no partner-side archive.")]),
            ("L-S08-3", "G-S08-1",
             "People avoid streets, schools, or clinics known to be dense with enrolled cars.",
             "R-S08-3",
             "The public is not given a live map of which cars are currently matching faces.",
             "Transparency can itself become a chilling-effect channel.",
             [A("R-S08-3-A1", "Coverage maps for dispatch will stay inside the authority UI.", "Open-data pressure and marketing maps."),
              A("R-S08-3-A2", "A blinking LED on the dashcam is not a usable tracker of matching state.", "It still signals something."),
              A("R-S08-3-A3", "Journalists will not scrape enrollment density from leaked APIs.", "They will try.")],
             [P("R-S08-3-P1", "cloud/search coordinator", "Public stats, if any, are delayed and aggregated at city level, not live car pins."),
              P("R-S08-3-P2", "phone companion app", "Do not show other users' enrollment on a map."),
              P("R-S08-3-P3", "dashcam firmware", "Do not advertise matching-active over Bluetooth beyond the paired phone.")]),
            ("L-S08-4", "G-S08-2",
             "A child bystander's face is enrolled into a gallery 'to improve child recall' without a parent.",
             "R-S08-4",
             "Children who are not the missing child are not added to any biometric gallery from dashcam footage.",
             "The obvious ML fix (more child faces) is itself a harm.",
             [A("R-S08-4-A1", "We can use crash-loop video as extra child training data because the owner consented.", "The child bystander did not."),
              A("R-S08-4-A2", "Blurred or synthetic children are enough to improve recall.", "May be true; should be tried before harvesting."),
              A("R-S08-4-A3", "Parents of bystanders will opt in via a public campaign.", "Response rates will be tiny and biased.")],
             [P("R-S08-4-P1", "person-recognition contractor", "Fine-tune corpora exclude unlabeled dashcam faces of minors."),
              P("R-S08-4-P2", "dashcam firmware", "No 'upload hard examples' path for non-match crops."),
              P("R-S08-4-P3", "cloud/search coordinator", "Reject training-ingest jobs whose source is production ChildFind crops.")]),
            ("L-S08-5", "G-S08-1",
             "An employer, landlord, or immigration officer obtains a still showing where a bystander was.",
             "R-S08-5",
             "A ChildFind still of a bystander is not obtainable by a private party who wants to know where that person was.",
             "The threat is not only the state.",
             [A("R-S08-5-A1", "Only dispatch can see stills.", "Parents, volunteers, drivers, and kiosk staff may also see them."),
              A("R-S08-5-A2", "A still without a name cannot be linked.", "Reverse image search and acquaintance recognition exist."),
              A("R-S08-5-A3", "NDAs bind volunteers.", "NDAs do not bind screenshots.")],
             [P("R-S08-5-P1", "cloud/search coordinator", "Minimize faces in a crop (subject-centered) and strip background license plates where feasible before a still leaves the device."),
              P("R-S08-5-P2", "cloud/search coordinator", "Watermark stills with the viewer id."),
              P("R-S08-5-P3", "phone companion app", "Drivers who confirm a match never receive a share button or a saved copy.")]),
            ("L-S08-6", "G-S08-1",
             "A bystander is stopped because they were next to a possible match in the same frame.",
             "R-S08-6",
             "Presence in the same video frame as a possible match does not by itself cause a bystander to be treated as a suspect companion.",
             "Association is a world harm the model does not even 'predict' explicitly.",
             [A("R-S08-6-A1", "Officers will treat other people in the crop as scenery.", "They will ask 'who is that adult'."),
              A("R-S08-6-A2", "Crops can be tightly boxed on the candidate child.", "Wide context helps reviewers, which conflicts."),
              A("R-S08-6-A3", "Companion identification is out of scope.", "Someone will add 'abductor model' later.")],
             [P("R-S08-6-P1", "dashcam firmware", "Default sighting still is a tight crop; a wider context image is available only behind a second dispatcher action."),
              P("R-S08-6-P2", "cloud/search coordinator", "UI copy: 'other people in the frame are not identified and are not suspects'."),
              P("R-S08-6-P3", "person-recognition model", "Do not emit identities or match_scores for additional faces in the context image.")]),
        ],
    )

    _add(
        analyses, decomps, "S09",
        ["freedom from mistaken police contact", "reputation", "caregiver liberty"],
        [G("G-S09-1", "Go about daily life without being treated as the missing child or their abductor"),
         G("G-S09-2", "Have a way to end a false identification quickly")],
        [
            ("L-S09-1", "G-S09-1",
             "Police stop a lookalike child in public based on a ChildFind pin.",
             "R-S09-1",
             "A child who is not the missing child is not stopped by police solely because a dashcam produced a possible-match notice.",
             "False-positive harm is the one developers underweight when they optimize recall.",
             [A("R-S09-1-A1", "Officers treat a possible-match notice as a lead that requires corroboration, not as an identification.", "Missing-child calls are emotional and fast."),
              A("R-S09-1-A2", "Lookalikes are rare enough that a high threshold prevents stops.", "School uniforms and age bands create many lookalikes."),
              A("R-S09-1-A3", "The caregiver can immediately show the child's identity.", "A child may have no ID; a caregiver may not be believed."),
              A("R-S09-1-A4", "The notice is shown only to dispatch, not blasted to every patrol phone as 'FOUND'.", "Someone will want a push to all units.")],
             [P("R-S09-1-P1", "cloud/search coordinator", "Every notice is labeled 'unconfirmed possible match' and includes match_score; there is no 'FOUND' state from software alone."),
              P("R-S09-1-P2", "cloud/search coordinator", "Do not fan a pin to all units; send it to the coordinating desk for assignment."),
              P("R-S09-1-P3", "person-recognition model", "Output match_score and a recommended-threshold band; do not output a binary identity claim."),
              P("R-S09-1-P4", "cloud/search coordinator", "Attach the search photo next to the still so a human compares before a stop is authorized.")]),
            ("L-S09-2", "G-S09-1",
             "The caregiver is arrested as an abductor because they are walking with a lookalike.",
             "R-S09-2",
             "An adult accompanying a child who is not missing is not arrested solely on a ChildFind possible-match.",
             "The 'abductor' inference is a world action with no supporting SPEC unless we invent one.",
             [A("R-S09-2-A1", "There is no abductor classifier in the system.", "Feature requests will add one."),
              A("R-S09-2-A2", "Officers will not treat 'adult + matching child' as kidnapping-in-progress.", "That is a common heuristic."),
              A("R-S09-2-A3", "The true missing-child bulletin includes whether an abductor is suspected.", "Sometimes it does not.")],
             [P("R-S09-2-P1", "cloud/search coordinator", "If the case file has no suspected-companion field, the notice UI omits any companion language."),
              P("R-S09-2-P2", "person-recognition model", "No abductor/companion score is emitted on the ChildFind path."),
              P("R-S09-2-P3", "cloud/search coordinator", "Require a dispatcher note before a companion-adult description is added to a unit's assignment.")]),
            ("L-S09-3", "G-S09-1",
             "A school or store goes into lockdown because a public app showed a nearby match.",
             "R-S09-3",
             "Schools and businesses do not receive automated ChildFind match alerts about children on their premises.",
             "The blast radius of a FP includes institutions.",
             [A("R-S09-3-A1", "There is no public match feed.", "Someone will build a Twitter bot."),
              A("R-S09-3-A2", "Drivers will not film the stop and tag the school.", "They will."),
              A("R-S09-3-A3", "The non-profit will not 'partner' with school apps.", "It is a tempting expansion.")],
             [P("R-S09-3-P1", "cloud/search coordinator", "No third-party webhook for match events other than the coordinating unit."),
              P("R-S09-3-P2", "phone companion app", "No share-to-social control on stills or pins."),
              P("R-S09-3-P3", "cloud/search coordinator", "Rate-limit and watermark to make scraping a live feed unattractive.")]),
            ("L-S09-4", "G-S09-2",
             "A lookalike's photo remains associated with the case online after the true child is found.",
             "R-S09-4",
             "Once a possible-match is judged to be the wrong child, that still is not kept as part of a public or family-visible case story.",
             "Correction has to be as operational as detection.",
             [A("R-S09-4-A1", "Dispatchers will mark false matches.", "Busy desks will not."),
              A("R-S09-4-A2", "Copies have not already left the system.", "They may have."),
              A("R-S09-4-A3", "The lookalike family even hears that they were in a still.", "Often they only hear via a stop.")],
             [P("R-S09-4-P1", "cloud/search coordinator", "A false-match disposition deletes or quarantines that still from family and volunteer views."),
              P("R-S09-4-P2", "cloud/search coordinator", "Propagate the disposition to any device that queued the same crop."),
              P("R-S09-4-P3", "cloud/search coordinator", "Keep a sealed audit copy only for complaint investigation, with a shorter TTL.")]),
            ("L-S09-5", "G-S09-1",
             "The lookalike child becomes afraid of cameras and of going outside.",
             "R-S09-5",
             "A mistaken ChildFind contact is followed by a clear, child-appropriate explanation that they are not in trouble and were not the missing child.",
             "Dignity after a FP is a world requirement on operators, not on the model.",
             [A("R-S09-5-A1", "Officers have a protocol for mistaken missing-child stops involving children.", "Many do not."),
              A("R-S09-5-A2", "The manufacturer is allowed to require training as a condition of API access.", "Agencies may refuse."),
              A("R-S09-5-A3", "The caregiver is present and calm.", "Not always.")],
             [P("R-S09-5-P1", "cloud/search coordinator", "When a unit is assigned, the assignment packet includes a mistaken-identity script checklist."),
              P("R-S09-5-P2", "cloud/search coordinator", "After a false-match disposition, prompt the unit to record whether the script was used."),
              P("R-S09-5-P3", "cloud/search coordinator", "Do not show the lookalike child's still to additional units after disposition.")]),
        ],
    )

    _add(
        analyses, decomps, "S10",
        ["lawful biometric processing", "children's data protection", "purpose limitation and auditability"],
        [G("G-S10-1", "Biometric processing of the public has a legal basis, limits, and a way to challenge it"),
         G("G-S10-2", "Children's data is treated as a special category, not as 'just another face'")],
        [
            ("L-S10-1", "G-S10-1",
             "The network performs biometric processing of the general public without a valid legal basis.",
             "R-S10-1",
             "Faces of people who are not the search subject are not biometrically processed except as a transient comparison during an authorized, time-bounded search.",
             "If this REQ fails, the feature is illegal even when it finds children.",
             [A("R-S10-1-A1", "Owner consent covers bystanders in public.", "It generally does not."),
             A("R-S10-1-A2", "A missing-child emergency exception covers continuous embedding of everyone.", "Exceptions are narrow and time-bounded."),
              A("R-S10-1-A3", "Offline processing on a dashcam is not 'processing' under the statute.", "It still is, in many regimes.")],
             [P("R-S10-1-P1", "dashcam firmware", "Start the matcher only after a valid search-alert with expiry is stored; stop at expiry."),
              P("R-S10-1-P2", "dashcam firmware", "Do not build a standing gallery; comparison is in-memory against the current search photo."),
              P("R-S10-1-P3", "cloud/search coordinator", "Record the legal-basis field on the search-id and refuse fan-out if it is empty.")]),
            ("L-S10-2", "G-S10-2",
             "Children's images move across borders to a contractor region without safeguards.",
             "R-S10-2",
             "A child's search photo and any matching still remain in the jurisdiction the case was opened in, unless a recorded transfer mechanism applies.",
             "Rekognition-like infrastructure is often multi-region by default.",
             [A("R-S10-2-A1", "The contractor's default region is the case region.", "Defaults are us-east-1."),
              A("R-S10-2-A2", "On-device matching avoids transfer entirely.", "Model updates and crash dumps may still leave."),
              A("R-S10-2-A3", "Authorities will not email stills to a personal Gmail.", "They will.")],
             [P("R-S10-2-P1", "person-recognition contractor", "Pin inference and storage to a region field on the search-id."),
              P("R-S10-2-P2", "cloud/search coordinator", "Block fan-out to a device whose last country code is outside the case region unless an override token is present."),
              P("R-S10-2-P3", "dashcam firmware", "Prefer on-device comparison so the search photo is the only child image that must be fanned out.")]),
            ("L-S10-3", "G-S10-1",
             "Accident-evidence recordings are silently joined to a police biometric store.",
             "R-S10-3",
             "Crash-loop recordings made for accident evidence are not searchable as a biometric database.",
             "Purpose limitation between the two product jobs.",
             [A("R-S10-3-A1", "Two stores (loop vs ChildFind) are technically and organizationally separate.", "One disk is cheaper."),
              A("R-S10-3-A2", "A warrant for a specific time window is how police get loop footage, as today.", "ChildFind will be pitched as skipping that."),
              A("R-S10-3-A3", "Owners understand they can still export a crash clip without enrolling in matching.", "UX may bundle them.")],
             [P("R-S10-3-P1", "dashcam firmware", "ChildFind matcher reads frames in RAM; it does not index the crash-loop archive by face."),
              P("R-S10-3-P2", "cloud/search coordinator", "No API that takes a photo and scans stored crash loops."),
              P("R-S10-3-P3", "phone companion app", "Crash export and ChildFind enrollment are separate toggles.")]),
            ("L-S10-4", "G-S10-1",
             "A subject cannot find out whether they were matched, or get deletion, because the system is opaque.",
             "R-S10-4",
             "A person who was the subject of a ChildFind still can have that still deleted through a defined request path once the search has closed, and can learn whether a still existed.",
             "Opaque ML systems fail access/deletion rights.",
             [A("R-S10-4-A1", "We can authenticate that the requester is the person in the still without collecting more biometrics.", "This is hard; a case-id + liaison path may be the only way."),
              A("R-S10-4-A2", "Offline devices will honor deletion when they next connect.", "Some never will."),
              A("R-S10-4-A3", "Law-enforcement copies are in scope of the same deletion.", "Often they are not.")],
             [P("R-S10-4-P1", "cloud/search coordinator", "After case-closed, expose a deletion/status request keyed by search-id to the liaison and to a DPA portal."),
              P("R-S10-4-P2", "dashcam firmware", "On receiving a delete(search-id) message, wipe queued stills and ack."),
              P("R-S10-4-P3", "cloud/search coordinator", "Track outstanding device acks for deletion and report incomplete deletion as a compliance status.")]),
            ("L-S10-5", "G-S10-2",
             "A precedent is set that any emotional child-safety story justifies biometric scanning of a city.",
             "R-S10-5",
             "Each search remains individually authorized, time-bounded, and geographically bounded rather than becoming a standing scan of all enrolled cameras.",
             "The 1-alert/day statistic is a design gift; ignore it and you get always-on scanning.",
             [A("R-S10-5-A1", "Rarity of alerts will keep political appetite limited.", "One viral case can change that."),
              A("R-S10-5-A2", "Geo-fences will stay tight around last-seen areas.", "Statewide fences are easier."),
              A("R-S10-5-A3", "Expiry will be short.", "Nobody will want to be the person who expired a search one hour too soon.")],
             [P("R-S10-5-P1", "cloud/search coordinator", "Require geo-fence + expiry on every search-id; default expiry is short and renewal is an explicit action."),
              P("R-S10-5-P2", "dashcam firmware", "Ignore alerts with empty fences or with expiry in the past."),
              P("R-S10-5-P3", "cloud/search coordinator", "Alert if a fence exceeds a configurable area or a renewal count exceeds a policy cap.")]),
        ],
    )

    _add(
        analyses, decomps, "S11",
        ["customer goodwill", "limited liability", "predictable operating cost"],
        [G("G-S11-1", "Host an edge drop-off without becoming a police checkpoint"),
         G("G-S11-2", "Not pay unbounded bandwidth or eat a lawsuit")],
        [
            ("L-S11-1", "G-S11-1",
             "Customers treat the station as a surveillance site and stop coming.",
             "R-S11-1",
             "Drivers using the station are not shown, and do not have to pass, a face-matching checkpoint to buy fuel.",
             "Edge computing excitement in the scenario is a product risk, not a free lunch.",
             [A("R-S11-1-A1", "The kiosk only offloads encrypted queues from cars that already enrolled, like a USB stick.", "Someone will point a camera at the forecourt."),
              A("R-S11-1-A2", "Signage can make this feel like Wi-Fi, not CCTV.", "A camera on a pole will not."),
              A("R-S11-1-A3", "Staff will not watch stills on a back-office monitor.", "They will if we give them a UI.")],
             [P("R-S11-1-P1", "edge kiosk", "Accept only encrypted sighting-report queues from authenticated dashcams; do not run a site-wide camera into the matcher."),
              P("R-S11-1-P2", "edge kiosk", "No staff UI that displays faces."),
              P("R-S11-1-P3", "cloud/search coordinator", "Do not list partner sites on a public 'coverage map'.")]),
            ("L-S11-2", "G-S11-2",
             "A child was at the pump and not reported; the station is sued for hosting the system.",
             "R-S11-2",
             "Hosting an offload kiosk is not treated as a promise that everyone on the forecourt will be matched.",
             "Coverage fiction again, now at a place.",
             [A("R-S11-2-A1", "The kiosk is not a camera.", "Press photos will show a camera-looking box."),
              A("R-S11-2-A2", "Contracts shift duty to the manufacturer.", "Plaintiffs still name the deep pocket they can find."),
              A("R-S11-2-A3", "Only enrolled cars offload, so most forecourt visitors are irrelevant.", "That is hard to explain after a miss.")],
             [P("R-S11-2-P1", "edge kiosk", "Broadcast a machine-readable 'offload only, no site matching' capability flag."),
              P("R-S11-2-P2", "cloud/search coordinator", "Do not count kiosk locations as camera coverage in dispatch density maps."),
              P("R-S11-2-P3", "phone companion app", "Partner-facing status page states offload-only in the same words used internally.")]),
            ("L-S11-3", "G-S11-1",
             "Someone uses the kiosk network to pull faces of all customers.",
             "R-S11-3",
             "The partner network cannot be queried for people who did not just offload an enrolled dashcam queue.",
             "A new shared phenomenon (the kiosk) is a new attack surface.",
             [A("R-S11-3-A1", "The kiosk has no camera and no disk of faces.", "Feature creep: 'why not match the forecourt camera we already have'."),
              A("R-S11-3-A2", "Physical access to the box does not yield keys.", "Gas-station closets are not data centers."),
              A("R-S11-3-A3", "The partner's IT staff have no admin API for stills.", "They will want one for 'support'.")],
             [P("R-S11-3-P1", "edge kiosk", "Forward-only: decrypt-at-coordinator; the kiosk stores opaque blobs with TTL."),
              P("R-S11-3-P2", "edge kiosk", "No query API; physical debug requires a manufacturer key and wipes on close."),
              P("R-S11-3-P3", "cloud/search coordinator", "Issue per-session keys so a stolen box cannot decrypt old blobs.")]),
            ("L-S11-4", "G-S11-2",
             "The kiosk is stolen or smashed and stored blobs are taken.",
             "R-S11-4",
             "Theft of a kiosk does not disclose identifiable stills or search photos.",
             "Physical security of edge is not like cloud security.",
             [A("R-S11-4-A1", "TTL is short enough that a stolen disk is empty.", "A busy holiday weekend queue may be large."),
              A("R-S11-4-A2", "Encryption keys are not on the same disk.", "They often are, for convenience."),
              A("R-S11-4-A3", "Thieves want cash, not blobs.", "Sometimes they want both.")],
             [P("R-S11-4-P1", "edge kiosk", "Encrypt blobs with keys the kiosk cannot use to decrypt; coordinator holds the unwrap."),
              P("R-S11-4-P2", "edge kiosk", "Wipe blobs older than TTL even if not yet forwarded."),
              P("R-S11-4-P3", "cloud/search coordinator", "Revoke a kiosk's forwarding identity when tamper or theft is reported.")]),
            ("L-S11-5", "G-S11-2",
             "Bandwidth bills from video offload exceed the partnership's value.",
             "R-S11-5",
             "The partner is not asked to carry raw video, only small encrypted reports within a contracted byte budget.",
             "If the design needs full video at the edge, the partnership dies or becomes extractive.",
             [A("R-S11-5-A1", "Sighting-reports are kilobytes, not gigabytes.", "If we offload unmatched clips 'just in case', they are not."),
              A("R-S11-5-A2", "Nightly sync is enough.", "Faster-is-more-useful fights this."),
              A("R-S11-5-A3", "The manufacturer pays overage.", "Unless the contract is silent.")],
             [P("R-S11-5-P1", "edge kiosk", "Refuse objects over a size cap; accept only sighting-report MIME types."),
              P("R-S11-5-P2", "dashcam firmware", "Build the kiosk offload from the same small sighting-report as the phone path."),
              P("R-S11-5-P3", "cloud/search coordinator", "Meter per-kiosk bytes and disable a site that exceeds contract rather than silently billing the partner.")]),
        ],
    )

    _add(
        analyses, decomps, "S12",
        ["income", "passenger privacy", "not being punished for opting out"],
        [G("G-S12-1", "Keep driving for a living without turning passengers into search subjects"),
         G("G-S12-2", "Not be deactivated for refusing ChildFind")],
        [
            ("L-S12-1", "G-S12-1",
             "A passenger is matched or still-captured without knowing a search was running in the car they hired.",
             "R-S12-1",
             "A rideshare passenger is not biometrically compared to a missing-child photo unless they have been told a search is active in that vehicle and can decline the ride.",
             "Employment dashcams break the consumer opt-in story.",
             [A("R-S12-1-A1", "Only the outward camera is used, so passengers are not in frame.", "Pickup happens at the curb, in frame; cabin cams exist."),
              A("R-S12-1-A2", "Platform terms cover this.", "Passengers do not read them; they may be unlawful anyway."),
              A("R-S12-1-A3", "A sticker on the window is notice.", "It is not a decline path.")],
             [P("R-S12-1-P1", "phone companion app", "In fleet mode, show a passenger-notice card before matching is allowed to run, and log the notice event."),
              P("R-S12-1-P2", "dashcam firmware", "Fleet mode binds matching to the outward camera and disables cabin input, same as R-S06-4."),
              P("R-S12-1-P3", "cloud/search coordinator", "Fleet organizations cannot hide the search-active state from the rider-facing notice.")]),
            ("L-S12-2", "G-S12-2",
             "The driver is deactivated or loses a bonus for turning ChildFind off.",
             "R-S12-2",
             "A driver who disables ChildFind does not automatically lose the ability to work.",
             "Otherwise 'opt-in' is fiction.",
             [A("R-S12-2-A1", "The fleet will treat ChildFind as optional safety theater.", "They will treat it as a KPI."),
              A("R-S12-2-A2", "The manufacturer does not send enrollment status to the fleet.", "The fleet will demand it."),
              A("R-S12-2-A3", "Local law forbids making employment conditional on biometric enrollment.", "Varies by city.")],
             [P("R-S12-2-P1", "cloud/search coordinator", "Do not provide an API whose only purpose is 'is this driver enrolled' to a fleet without a passenger-privacy role."),
              P("R-S12-2-P2", "phone companion app", "Driver opt-out does not emit a punishment-ready flag; it emits search-degraded like any other device."),
              P("R-S12-2-P3", "cloud/search coordinator", "Fleet dashboards show aggregate coverage, not named opt-out lists.")]),
            ("L-S12-3", "G-S12-1",
             "A passenger gives a one-star review because a match prompt or LED made them feel watched.",
             "R-S12-3",
             "Passengers are not shown missing-child photos or match stills during a trip.",
             "UX meant for volunteer drivers is wrong in a taxi.",
             [A("R-S12-3-A1", "We already suppressed driver prompts while moving.", "A passenger phone might still be used as the paired device."),
              A("R-S12-3-A2", "LEDs can be dimmed.", "Platforms may require a recording LED."),
              A("R-S12-3-A3", "Explanation at pickup is enough to prevent the feeling of being watched.", "It can also increase it.")],
             [P("R-S12-3-P1", "phone companion app", "Fleet mode disables all match previews on any paired phone in the vehicle."),
              P("R-S12-3-P2", "dashcam firmware", "No in-cabin display of crops."),
              P("R-S12-3-P3", "cloud/search coordinator", "Reviewer stills never route to a rider-facing app.")]),
            ("L-S12-4", "G-S12-1",
             "Footage of a fare dispute is pulled because it happened to be in a ChildFind queue.",
             "R-S12-4",
             "A passenger–driver dispute is not investigated through ChildFind stills collected for a missing-child search.",
             "Secondary use inside the same car.",
             [A("R-S12-4-A1", "ChildFind stills are useless for dispute resolution because they are tight face crops of people on the street.", "A wide FOV at pickup will include the passenger."),
              A("R-S12-4-A2", "Platforms already have a separate cabin-cam process.", "They will still ask for whatever exists."),
              A("R-S12-4-A3", "Purpose tokens hold under a platform lawyer's request.", "Pressure will be high.")],
             [P("R-S12-4-P1", "cloud/search coordinator", "Refuse platform-support accessors on the ChildFind store; send them to the crash-loop/warrant path."),
              P("R-S12-4-P2", "dashcam firmware", "Tag ChildFind blobs with purpose=missing-child so they cannot be pulled by the dispute export job."),
              P("R-S12-4-P3", "phone companion app", "No 'download today's stills' for the driver.")]),
            ("L-S12-5", "G-S12-2",
             "The driver's personal phone plan is billed for fleet matching uploads.",
             "R-S12-5",
             "Cellular bytes used for ChildFind on a fleet vehicle are not charged to the driver's personal plan without their agreement.",
             "Same data-cost REQ as S01, but the payer is different.",
             [A("R-S12-5-A1", "The paired phone is a company device.", "Often it is the driver's phone."),
              A("R-S12-5-A2", "OEM telematics will carry the bytes.", "Aftermarket cameras will not."),
              A("R-S12-5-A3", "Drivers notice the budget UI.", "They are busy.")],
             [P("R-S12-5-P1", "phone companion app", "In fleet mode, require a fleet-paid network identity or a pre-set budget bound to the organization, not the driver's personal default."),
              P("R-S12-5-P2", "dashcam firmware", "Prefer kiosk/Wi-Fi offload on fleet vehicles."),
              P("R-S12-5-P3", "cloud/search coordinator", "Billable-byte reports go to the fleet org, not to the driver email.")]),
        ],
    )


# Fix a syntax error above: extra closing paren in S11 L3 asms.
# The _fill function is the source of truth; validate on import via seed().
