"""Seed a reviewed, assignment-scale analysis into workspace/ without calling an LLM.

The LLM pipeline (`python -m hazard_tool stakeholders` etc.) is the supported way
to regenerate this analysis. This module exists so the committed report is
reproducible when no API key is present, and so the report renderer can be tested.
Content was written and then manually tightened for Jackson's world/machine split.
"""

from __future__ import annotations

from typing import Any

from . import io_util
from .catalog_lib import A, G, P, S, decomp, item
from .render import render_report


STAKEHOLDERS = [
    S("S01", "Dashcam owner / driver", "direct",
      "Person who bought or was given the dashcam and whose car generates footage.",
      "They control power, pairing, opt-in, and are the first privacy surface.",
      "medium", "medium"),
    S("S02", "Missing child (search subject)", "indirect",
      "The child the authorized search is trying to locate.",
      "The system's stated beneficiary; harms to them are the point of safety analysis.",
      "low", "high"),
    S("S03", "Parent / guardian of the missing child", "indirect",
      "Family coordinating with the non-profit and authorities.",
      "They live with false hope, delays, and leakage of family information.",
      "medium", "high"),
    S("S04", "Law enforcement / coordinating authorities", "direct",
      "Officers and dispatchers who issue searches and act on sightings.",
      "They are the actuator that turns a report into a real-world intervention.",
      "high", "medium"),
    S("S05", "Child-safety non-profit", "direct",
      "Partner that coordinates searches and public trust around child recovery.",
      "They hold the mission and the photo pipeline; a scandal ends the feature.",
      "high", "medium"),
    S("S06", "Automotive OEM", "direct",
      "Car manufacturer that may factory-install the dashcam.",
      "OEM contracts are the company's growth path and a vehicle-safety liability path.",
      "high", "low"),
    S("S07", "Person-recognition contractor", "direct",
      "Vendor that supplies and helps fine-tune the person/face recognition stack.",
      "Their model is the ML component; their cloud/on-device choices change the threat model.",
      "medium", "low"),
    S("S08", "Bystander / other road user", "indirect",
      "Pedestrians, other drivers, and passengers whose faces appear in footage.",
      "Most faces the model will ever see are not missing children; they bear biometric risk.",
      "low", "high"),
    S("S09", "Innocent lookalike child and caregiver", "indirect",
      "A child or adult who resembles the search photo, and the adult with them.",
      "False positives cause police contact, which is a different harm than a miss.",
      "low", "high"),
    S("S10", "Privacy regulator / data-protection authority", "indirect",
      "Agency enforcing biometric, children's-data, and purpose-limitation rules.",
      "Unlawful processing can shut the product down regardless of detection accuracy.",
      "high", "low"),
    S("S11", "Gas-station / edge-kiosk partner", "direct",
      "Business hosting drop-off or inference hardware that management wants to explore.",
      "The scenario explicitly invites edge computing; it creates a new surveillance place.",
      "medium", "medium"),
    S("S12", "Rideshare / fleet driver", "direct",
      "Driver whose vehicle is a workplace and who may be required to keep the dashcam on.",
      "Passengers did not buy the dashcam; employment pressure changes opt-in assumptions.",
      "low", "high"),
]


def _analysis_bundle() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Return (analyses, decompositions). Kept in one function so ids stay aligned."""
    analyses: list[dict[str, Any]] = []
    decomps: list[dict[str, Any]] = []

    def add(sh_id: str, values: list[str], goals: list, items_spec: list):
        items = []
        for lid, gid, loss, rid, req, note, asms, specs in items_spec:
            items.append(item(lid, gid, loss, rid, req, note))
            decomps.append(decomp(rid, sh_id, gid, loss, req, asms, specs))
        analyses.append({
            "stakeholder_id": sh_id,
            "values": values,
            "goals": goals,
            "items": items,
        })

    # ---------- S01 driver ----------
    add(
        "S01",
        ["privacy of their own driving record", "affordable operation", "undistracted driving", "agency over the device"],
        [G("G-S01-1", "Keep the dashcam useful as accident evidence without turning the car into a public search node"),
         G("G-S01-2", "Avoid surprise cost, crash risk, or legal blowback from ChildFind")],
        [
            ("L-S01-1", "G-S01-1",
             "The owner's everyday driving video and face embeddings are retained or reused after an authorized search ends.",
             "R-S01-1",
             "After an authorized search expires, people and vehicles recorded by the owner's dashcam are not identifiable from anything retained for ChildFind.",
             "Primary product promise of the dashcam is private evidence, not a biometric database.",
             [A("R-S01-1-A1", "Owners understand and can refuse enrollment in ChildFind before any search photo is applied to their footage.", "Dark-pattern opt-in and OEM-installed defaults are common."),
              A("R-S01-1-A2", "When a search ends, every copy of embeddings and crops derived from this car is actually deleted, including contractor caches.", "Contractor stacks like Rekognition often retain artifacts for debugging."),
              A("R-S01-1-A3", "A paired phone is not silently backing up raw clips to a personal cloud the owner forgot about.", "Phone OS backups are outside the dashcam company's control.")],
             [P("R-S01-1-P1", "dashcam firmware", "On search expiry, delete on-device search photos, embeddings, and queued sighting-reports and emit a deletion-complete status."),
              P("R-S01-1-P2", "cloud/search coordinator", "On expiry, send a revoke message to every enrolled device and contractor endpoint that previously received that search-id."),
              P("R-S01-1-P3", "phone companion app", "Do not upload raw video for ChildFind; if a clip is sent, send only the still attached to an explicit sighting-report.")]),
            ("L-S01-2", "G-S01-2",
             "The owner receives an unexpected cellular bill because ChildFind uploaded video through their phone.",
             "R-S01-2",
             "The owner is not billed for cellular data used by ChildFind beyond a limit they accepted in advance.",
             "Data-charge fear is named in the scenario and will drive silent opt-out.",
             [A("R-S01-2-A1", "The phone's cellular path is the only way a queued report leaves the car, so byte volume on that path equals user-visible cost.", "OEM telematics or Wi-Fi at home may carry traffic the user does not attribute to ChildFind."),
              A("R-S01-2-A2", "The owner notices and can act on an in-app data budget before the carrier bills them.", "Carrier bills lag; many users never open the companion app."),
              A("R-S01-2-A3", "Wi-Fi hotspots used for upload are free or already paid.", "Captive-portal Wi-Fi can still meter or fail over to cellular.")],
             [P("R-S01-2-P1", "phone companion app", "Count ChildFind uplink bytes and stop cellular uploads when the user-set budget is reached, emitting a budget-exceeded status."),
              P("R-S01-2-P2", "dashcam firmware", "Prefer Wi-Fi and USB offload; mark reports as cellular-eligible only if the phone app has advertised remaining budget."),
              P("R-S01-2-P3", "phone companion app", "Show a pre-enrollment estimate of worst-case bytes per search-day given the local search frequency.")]),
            ("L-S01-3", "G-S01-2",
             "A ChildFind match notification distracts the driver and contributes to a crash.",
             "R-S01-3",
             "While the vehicle is moving, the driver is not prompted to inspect a possible-match image.",
             "Driving safety dominates child-search UX; a crash makes the feature indefensible to OEMs.",
             [A("R-S01-3-A1", "The companion app can reliably know whether the vehicle is in motion from the dashcam or car speed signal.", "Bluetooth dropouts and aftermarket installs may not see speed."),
              A("R-S01-3-A2", "Passengers, not drivers, are the ones holding the phone when a prompt appears.", "The driver is often the only occupant."),
              A("R-S01-3-A3", "A sound or HUD flash is not enough to take the driver's eyes off the road.", "Any salient alert can still cause a glance.")],
             [P("R-S01-3-P1", "phone companion app", "Suppress match-preview UI and audible alerts whenever the last speed sample is above a parked threshold."),
              P("R-S01-3-P2", "dashcam firmware", "Do not display match images on any in-vehicle screen; only queue a silent sighting-report."),
              P("R-S01-3-P3", "cloud/search coordinator", "If a human review is required, route thumbnails to the non-profit reviewer interface, not to the moving driver.")]),
            ("L-S01-4", "G-S01-2",
             "After a child is found near the owner's route, the owner is blamed or sued for not reporting.",
             "R-S01-4",
             "An owner who had the device powered and enrolled is not treated as having a personal duty to have noticed the child.",
             "Legal duty-to-rescue confusion will chill adoption.",
             [A("R-S01-4-A1", "Courts and the public distinguish automated search from a human who saw the child.", "Headlines will not."),
              A("R-S01-4-A2", "Enrollment terms are presented before first use and retained.", "OEM-installed units may never show terms to the driver."),
              A("R-S01-4-A3", "Logs exist that show whether a search-alert was even on the device that day.", "Offline devices cannot prove they never received the alert.")],
             [P("R-S01-4-P1", "cloud/search coordinator", "Record per-device whether a search-alert was delivered, acknowledged, and whether any sighting-report was emitted."),
              P("R-S01-4-P2", "phone companion app", "Display that ChildFind is automated matching, not a request that the driver watch the road for a face."),
              P("R-S01-4-P3", "dashcam firmware", "Keep a tamper-evident log of search-id active windows and power state.")]),
            ("L-S01-5", "G-S01-1",
             "Always-on matching drains the battery or fills storage so the dashcam is dead when a crash happens.",
             "R-S01-5",
             "The dashcam continues to record a crash loop even when a ChildFind search is active.",
             "The product's original job is crash evidence; cannibalizing it is an organizational own-goal.",
             [A("R-S01-5-A1", "The unit is on vehicle power whenever the car is moving.", "Parking-mode battery packs are common."),
              A("R-S01-5-A2", "Person detection is cheap enough that crash-loop writes still keep up.", "Low-end models cannot run both."),
              A("R-S01-5-A3", "Owners will plug the camera back in after a low-battery shutdown.", "Many will not.")],
             [P("R-S01-5-P1", "dashcam firmware", "Treat crash-loop recording as a higher-priority write path than person-matching; drop matching when free space or voltage is below a reserved threshold."),
              P("R-S01-5-P2", "dashcam firmware", "Expose a power-state sample to the phone app when matching is shed."),
              P("R-S01-5-P3", "phone companion app", "If matching is shed, emit a search-degraded status so coordinators do not assume coverage.")]),
            ("L-S01-6", "G-S01-1",
             "Someone uses a fake 'missing child' enrollment to reconstruct the owner's routine from sighting metadata.",
             "R-S01-6",
             "A person who is not the subject of a bona fide, authority-backed search cannot obtain a trail of where the owner's car has been.",
             "The search channel is a location oracle if authorization is weak.",
             [A("R-S01-6-A1", "Only authorities/non-profit can create a search-id, and they vet the requester.", "Legal details are explicitly unsettled in the scenario."),
              A("R-S01-6-A2", "Sighting-reports are not visible to the requester, only to the coordinating unit.", "Product pressure will be to give parents a live map."),
              A("R-S01-6-A3", "A search photo of an adult cannot be submitted under a child-search type.", "Nothing in the current legal process prevents this.")],
             [P("R-S01-6-P1", "cloud/search coordinator", "Accept new search-ids only from authenticated authority/non-profit accounts, not from end-user accounts."),
              P("R-S01-6-P2", "cloud/search coordinator", "Do not return sighting GPS to the original requester account; only to the coordinating-unit inbox."),
              P("R-S01-6-P3", "cloud/search coordinator", "Reject search packets whose metadata mark the subject as 18+ or whose photo fails a child-age gate.")]),
        ],
    )

    # ---------- S02 missing child ----------
    add(
        "S02",
        ["physical safety", "speed of recovery", "dignity after recovery"],
        [G("G-S02-1", "Be found while still in the area where a participating camera saw them"),
         G("G-S02-2", "Not be further harmed by how the search is conducted or publicized")],
        [
            ("L-S02-1", "G-S02-1",
             "The child remains missing even though they walked through a participating camera's view.",
             "R-S02-1",
             "If a missing child is physically visible in the field of view of a participating dashcam during an authorized search, the coordinating law-enforcement unit learns of that co-location while the child is still in the same local area.",
             "This is the core mission requirement; it depends on the ML model and on radios the dashcam does not have.",
             [A("R-S02-1-A1", "The dashcam is powered and the lens is unobstructed whenever the vehicle is on a public road.", "Parking-mode off, dirty lenses, and winter covers are common."),
              A("R-S02-1-A2", "The child's face or other distinctive appearance is not fully covered for the entire time they are in view.", "Abductors adapt once the system is known; weather gear hides faces."),
              A("R-S02-1-A3", "Within a short interval after the child is in view, the dashcam or paired phone obtains a network path that can deliver a small report.", "The product has no native Internet; cars park far from phones."),
              A("R-S02-1-A4", "The search packet contains a photograph that still resembles the child's current appearance.", "Children change clothes, hair, and even face shape; photos may be years old."),
              A("R-S02-1-A5", "Operators read inbound sighting notices rather than discarding them as noise.", "False-positive floods train operators to ignore the channel.")],
             [P("R-S02-1-P1", "phone companion app", "On receiving a search-alert (photo, search-id, geographic scope, expiry), store it until expiry and forward it to the paired dashcam."),
              P("R-S02-1-P2", "person-recognition model", "For each in-scope person crop, output a match_score against the search photo."),
              P("R-S02-1-P3", "dashcam firmware", "When match_score exceeds the configured threshold, emit a sighting-report containing search-id, timestamp, GPS sample, and a cropped still."),
              P("R-S02-1-P4", "dashcam firmware", "If no radio is up, queue the sighting-report until the next successful Bluetooth/Wi-Fi/USB session or until search expiry."),
              P("R-S02-1-P5", "cloud/search coordinator", "On ingesting a sighting-report, present it in the coordinating-unit inbox with map pin and still, without requiring a second model pass that can drop it.")]),
            ("L-S02-2", "G-S02-2",
             "A public or in-app alert warns an abductor, who relocates the child before officers arrive.",
             "R-S02-2",
             "An abductor traveling with the child does not receive a real-time notice that a nearby camera just matched the child.",
             "Faster reports help authorities only if they are not also faster reports to the offender.",
             [A("R-S02-2-A1", "Drivers do not get a push that names the child and shows 'match nearby' on a lock screen.", "Marketing will want visible 'you helped' moments."),
              A("R-S02-2-A2", "The abductor is not also a enrolled ChildFind user who receives the same search-alert photo.", "Anyone can buy a dashcam."),
              A("R-S02-2-A3", "Officers can intercept without a public crowd converging.", "Amber-style publicity is the default mental model.")],
             [P("R-S02-2-P1", "phone companion app", "Do not display the search photo or 'match nearby' to the driver; only a generic 'search active in region' state if anything."),
              P("R-S02-2-P2", "cloud/search coordinator", "Hold sighting-reports in the authority inbox; do not fan them out to all enrolled devices."),
              P("R-S02-2-P3", "cloud/search coordinator", "Delay any public non-profit bulletin until after the coordinating unit marks the sighting as acted-on or expired.")]),
            ("L-S02-3", "G-S02-2",
             "The recovered child is filmed, identified, and the still circulates on social media.",
             "R-S02-3",
             "After recovery, the child's face from ChildFind stills is not available to the general public.",
             "Rescue can become a second victimization.",
             [A("R-S02-3-A1", "Officers and reviewers do not screenshot the inbox.", "They will."),
              A("R-S02-3-A2", "Drivers never see a high-resolution crop they can share.", "If we prompt drivers to confirm, they see the face."),
              A("R-S02-3-A3", "News media cannot FOIA the stills in identifiable form.", "Public-records law varies and is unsettled here.")],
             [P("R-S02-3-P1", "cloud/search coordinator", "Watermark reviewer stills and disable download by default; store access logs per still."),
              P("R-S02-3-P2", "cloud/search coordinator", "On case-closed, delete or irreversibly blur face crops in all ChildFind stores."),
              P("R-S02-3-P3", "phone companion app", "If a driver confirmation UI exists, show a time-limited low-resolution thumbnail that cannot be screenshotted via OS flags where available.")]),
            ("L-S02-4", "G-S02-1",
             "Search resources chase a lookalike while the actual child is moved elsewhere.",
             "R-S02-4",
             "A false sighting does not cause the only available officers in the true vicinity to leave that vicinity.",
             "False positives are not a victimless precision metric; they steal time from the child.",
             [A("R-S02-4-A1", "Dispatch has more than one unit and will not redeploy the last local unit on a low-confidence pin.", "Rural areas have one unit."),
              A("R-S02-4-A2", "Confidence scores correspond to real-world chance it is the child.", "Face scores are poorly calibrated, especially for children."),
              A("R-S02-4-A3", "Multiple independent pins are required before a full redeploy.", "Pressure to 'do something' after a ping is high.")],
             [P("R-S02-4-P1", "cloud/search coordinator", "Attach match_score, number of supporting frames, and 'unconfirmed' to every sighting-report shown to dispatch."),
              P("R-S02-4-P2", "cloud/search coordinator", "If only one unit covers the true last-known area, flag a single low-score pin as 'do not abandon last-known'."),
              P("R-S02-4-P3", "person-recognition model", "Output a calibrated score or an explicit low-confidence band rather than a binary match bit.")]),
            ("L-S02-5", "G-S02-1",
             "The child is in view but disguised or too young for an adult-tuned face model, so no one looks at the frame.",
             "R-S02-5",
             "A missing young child who is visibly present and unoccluded in a participating camera's view is not overlooked solely because they are a small child rather than an adult.",
             "Contractor expertise in distorted/low-light adult faces is the wrong domain.",
             [A("R-S02-5-A1", "A face model trained mostly on adults transfers to toddlers and school-age children.", "It generally does not; faces and identification cues differ."),
              A("R-S02-5-A2", "Clothing, height, and companion adult are stable enough to use as a backup cue.", "Clothes change; the companion may be the abductor."),
              A("R-S02-5-A3", "The search photo is a recent, frontal, well-lit picture of this child.", "Amber packets are often old school portraits.")],
             [P("R-S02-5-P1", "person-recognition model", "Expose a child-specific operating mode or a separate child embedding head; output match_score for the search photo under that mode."),
              P("R-S02-5-P2", "dashcam firmware", "When face match_score is below threshold but a person crop is in-scope, emit a top-k candidate still for reviewer UI rather than dropping the frame."),
              P("R-S02-5-P3", "cloud/search coordinator", "Let reviewers filter by clothing-color tags supplied in the search packet, not only by face score.")]),
            ("L-S02-6", "G-S02-2",
             "The child's last known location is published so precisely that a dangerous guardian finds them first.",
             "R-S02-6",
             "A person who is a threat to the child does not obtain a live, meter-accurate location from ChildFind.",
             "Custody and domestic-violence cases are common in missing-child reports.",
             [A("R-S02-6-A1", "The coordinating unit has already screened which adult may receive location updates.", "Intake is rushed."),
              A("R-S02-6-A2", "Parents using the non-profit portal are the safe parents.", "Sometimes they are not."),
              A("R-S02-6-A3", "Coarse city-level public alerts are enough for the public, so precise GPS can stay inside dispatch.", "Product demos will show a live map.")],
             [P("R-S02-6-P1", "cloud/search coordinator", "Separate the parent-status feed (search active / child recovered) from the GPS-bearing sighting inbox."),
              P("R-S02-6-P2", "cloud/search coordinator", "Require a two-person authority acknowledgement before any GPS-bearing still is exported."),
              P("R-S02-6-P3", "cloud/search coordinator", "Redact GPS to a coarse geohash on any non-dispatch role.")]),
        ],
    )

    # ---------- S03 parent ----------
    add(
        "S03",
        ["hope grounded in truth", "speed", "family privacy"],
        [G("G-S03-1", "Get timely, truthful information that helps recover the child"),
         G("G-S03-2", "Not have the family's other children or address exposed by the search")],
        [
            ("L-S03-1", "G-S03-1",
             "Parents are told of 'possible sightings' that are not their child, then crash emotionally and stop trusting later true reports.",
             "R-S03-1",
             "Parents are not notified of a sighting unless the coordinating unit has judged it worth acting on.",
             "Unfiltered model output is not a family communication channel.",
             [A("R-S03-1-A1", "Parents want every ping.", "They say that on day one and regret it by ping ten."),
              A("R-S03-1-A2", "A reviewer is available 24/7 to filter.", "Volunteer capacity is bursty."),
              A("R-S03-1-A3", "Withholding unconfirmed pings will not be described as 'the company hid sightings'.", "It will, if a child is later found near an unpublished pin.")],
             [P("R-S03-1-P1", "cloud/search coordinator", "Parent-facing events are only those marked released-to-family by the coordinating unit, not raw sighting-reports."),
              P("R-S03-1-P2", "cloud/search coordinator", "Keep an audit log of withheld pins so a later inquiry can show they were reviewed."),
              P("R-S03-1-P3", "cloud/search coordinator", "Rate-limit family notifications to a configured maximum per hour.")]),
            ("L-S03-2", "G-S03-1",
             "A real nearby sighting sits in a queue while parents are told 'no new information'.",
             "R-S03-2",
             "When a sighting is judged actionable, the parents (or their designated liaison) hear about it before the information is stale.",
             "Delay is a different failure from silence after a miss.",
             [A("R-S03-2-A1", "Someone is on duty to make the 'actionable' judgment quickly.", "Night and weekend gaps."),
              A("R-S03-2-A2", "The liaison phone number in the case file still works.", "Families in crisis change phones."),
              A("R-S03-2-A3", "Parents are in a position to hear a call (not driving, not in the air).", "Not always.")],
             [P("R-S03-2-P1", "cloud/search coordinator", "SLA-timestamp the gap between sighting ingest and released-to-family; page an on-call reviewer when the gap exceeds a threshold."),
              P("R-S03-2-P2", "cloud/search coordinator", "Support multiple liaison contacts and a fallback to the coordinating unit if all fail."),
              P("R-S03-2-P3", "phone companion app", "If the liaison is an enrolled user, deliver the released notice over the same authenticated channel as the case.")]),
            ("L-S03-3", "G-S03-2",
             "The search packet includes a home address and photos of siblings that then leak.",
             "R-S03-3",
             "Home address and images of children who are not the missing child do not leave the coordinating unit's custody.",
             "Search packets are over-broad because intake copies the whole case file.",
             [A("R-S03-3-A1", "Intake staff will minimize the packet to one recent photo and a last-seen area.", "They paste the whole flyer."),
              A("R-S03-3-A2", "Enrolled dashcams never display the packet.", "If drivers confirm matches, they see it."),
              A("R-S03-3-A3", "Contractor training pipelines will not scrape production packets.", "Unless contracts forbid it and we check.")],
             [P("R-S03-3-P1", "cloud/search coordinator", "Search-alert schema allows only: search-id, subject photo(s), age band, clothing tags, geo-fence, expiry — no address field."),
              P("R-S03-3-P2", "cloud/search coordinator", "Strip EXIF and additional faces from photos before fan-out to devices."),
              P("R-S03-3-P3", "person-recognition contractor", "Contractual SPEC: production search photos are not written into the fine-tune corpus.")]),
            ("L-S03-4", "G-S03-2",
             "A sibling or the searching parent is matched as the 'abductor' or as the child and is detained.",
             "R-S03-4",
             "Family members who are with the missing child's siblings in public are not detained solely because a ChildFind score fired on a related face.",
             "Related faces are a known failure mode of face systems.",
             [A("R-S03-4-A1", "The system can tell a sibling from the subject.", "Often it cannot."),
              A("R-S03-4-A2", "Officers will ask a clarifying question before a stop.", "Fast-moving missing-child calls produce the opposite."),
              A("R-S03-4-A3", "The family is not simultaneously the suspect in the case.", "Sometimes they are, which needs a different protocol, not a model.")],
             [P("R-S03-4-P1", "cloud/search coordinator", "Allow the coordinating unit to attach do-not-confuse reference photos of siblings that suppress a sighting-report if the best match is a sibling id."),
              P("R-S03-4-P2", "person-recognition model", "When two enrolled identities are both above threshold, output both ids rather than argmax-only."),
              P("R-S03-4-P3", "cloud/search coordinator", "Label such reports 'possible related-face' in the dispatch UI.")]),
            ("L-S03-5", "G-S03-1",
             "The search is quietly ended because the non-profit is flooded, and parents are not told the network is no longer looking.",
             "R-S03-5",
             "Parents know whether participating cameras are still being asked to search for their child.",
             "Operational degradation must be visible to the people who think a net is out there.",
             [A("R-S03-5-A1", "A search-id remaining 'open' in a database means devices still have the alert.", "Revocation can fail on offline devices."),
              A("R-S03-5-A2", "Parents interpret 'case open' as 'cameras are searching'.", "Those are different."),
              A("R-S03-5-A3", "Coverage maps shown to families match devices that actually acknowledged the alert.", "Acks never arrive from offline units.")],
             [P("R-S03-5-P1", "cloud/search coordinator", "Expose to the liaison a coverage statistic: count of devices that acknowledged the current search-id in the geo-fence in the last T hours."),
              P("R-S03-5-P2", "dashcam firmware", "Whenever a radio session starts, send an ack for each still-active search-id."),
              P("R-S03-5-P3", "cloud/search coordinator", "If ack count in the fence drops below a floor, mark the family status 'limited camera coverage' rather than 'searching'.")]),
        ],
    )

    return analyses, decomps


def remaining_stakeholders() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """S04–S12. Split for file size; called by seed()."""
    analyses: list[dict[str, Any]] = []
    decomps: list[dict[str, Any]] = []

    def add(sh_id: str, values: list[str], goals: list, items_spec: list):
        items = []
        for lid, gid, loss, rid, req, note, asms, specs in items_spec:
            items.append(item(lid, gid, loss, rid, req, note))
            decomps.append(decomp(rid, sh_id, gid, loss, req, asms, specs))
        analyses.append({
            "stakeholder_id": sh_id,
            "values": values,
            "goals": goals,
            "items": items,
        })

    add(
        "S04",
        ["effective recovery", "lawful process", "scarce officer time"],
        [G("G-S04-1", "Receive sightings that are timely, located, and worth sending a unit"),
         G("G-S04-2", "Not create an unlawful or indefensible search record")],
        [
            ("L-S04-1", "G-S04-1",
             "Dispatch burns a shift on false pins and has no unit left for a later true pin.",
             "R-S04-1",
             "A ChildFind notice does not cause officers to abandon a higher-priority last-known area without a human decision.",
             "The model must not be allowed to steer cars by itself.",
             [A("R-S04-1-A1", "A dispatcher always stands between a pin and a unit.", "Staffing gaps; 'auto-assign nearest unit' will be proposed."),
              A("R-S04-1-A2", "Units will wait for a confidence label they understand.", "A red map pin is treated as certainty."),
              A("R-S04-1-A3", "The last-known area is still the prior.", "Anchoring on a new ping is strong.")],
             [P("R-S04-1-P1", "cloud/search coordinator", "Do not emit an auto-dispatch command; emit a sighting-notice that requires an acknowledge-to-assign action."),
              P("R-S04-1-P2", "cloud/search coordinator", "Show last-known area and the new pin on the same map with the unconfirmed label."),
              P("R-S04-1-P3", "person-recognition model", "Provide match_score on the notice, not a binary 'found'.")]),
            ("L-S04-2", "G-S04-1",
             "A true sighting arrives hours later, after the child has left the area.",
             "R-S04-2",
             "When a participating camera had the child in view, dispatch has the notice while a search of that area can still succeed.",
             "Connectivity, not just accuracy, sets whether 'faster is more useful' is true.",
             [A("R-S04-2-A1", "The paired phone is in the car with Bluetooth up.", "Phones are in houses, offices, and pockets far from parked cars."),
              A("R-S04-2-A2", "Search-alerts are already on the device before the child is seen, so matching is local.", "Without Internet, the alert may arrive after the footage is overwritten."),
              A("R-S04-2-A3", "Loop footage is retained long enough for a delayed alert to be applied retroactively.", "Cheap units keep minutes, not hours.")],
             [P("R-S04-2-P1", "cloud/search coordinator", "Fan out search-alerts to devices that last reported a GPS sample inside an expanded fence, not only to devices currently online."),
              P("R-S04-2-P2", "dashcam firmware", "On receiving a search-alert, run matching over retained loop footage for the alert's time window, not only over future frames."),
              P("R-S04-2-P3", "phone companion app", "When a radio session starts, drain the sighting-report queue before other telemetry.")]),
            ("L-S04-3", "G-S04-2",
             "A stop or search based on ChildFind is thrown out, and the case is damaged.",
             "R-S04-3",
             "Officers acting on a ChildFind notice can show a lawful, purpose-limited, time-bounded authorization for that search-id.",
             "Legal details are unsettled; the machine must still leave a paper trail.",
             [A("R-S04-3-A1", "An authorized search-id corresponds to a real missing-child case, not a fishing expedition.", "Mission creep is a stated risk."),
              A("R-S04-3-A2", "The geo-fence and expiry on the alert match the warrant or policy instrument.", "Copy-paste fences will be statewide 'just in case'."),
              A("R-S04-3-A3", "Device logs are admissible and complete.", "Offline gaps look like spoliation.")],
             [P("R-S04-3-P1", "cloud/search coordinator", "Persist the legal/authorization token, geo-fence, and expiry with the search-id and show them on every sighting-notice."),
              P("R-S04-3-P2", "dashcam firmware", "Refuse to run matching if the search-alert lacks expiry or authorization-id fields."),
              P("R-S04-3-P3", "cloud/search coordinator", "Export a chain-of-custody package: alert, device ack, still, GPS, timestamps.")]),
            ("L-S04-4", "G-S04-2",
             "The same pipeline is reused for shoplifting, immigration, or protest monitoring.",
             "R-S04-4",
             "Person matching on consumer dashcams is not applied to a purpose other than an authorized missing-child search.",
             "Once the camera network exists, other agencies will ask.",
             [A("R-S04-4-A1", "Contractual purpose limitation will be respected under political pressure.", "It often is not."),
              A("R-S04-4-A2", "A 'missing child' label on a packet means the subject is a child in a genuine case.", "Labels can be lied about."),
              A("R-S04-4-A3", "OEMs and the non-profit will walk away if purpose expands, creating a real brake.", "Unless revenue replaces them.")],
             [P("R-S04-4-P1", "cloud/search coordinator", "Hard-code the search type enum to missing-child and drop any other type at the API boundary."),
              P("R-S04-4-P2", "dashcam firmware", "Ignore search-alerts whose type field is not missing-child."),
              P("R-S04-4-P3", "cloud/search coordinator", "Publish an append-only audit of search-ids issued (metadata only) to the non-profit's compliance role.")]),
            ("L-S04-5", "G-S04-1",
             "Operators ignore the inbox because yesterday it was 400 low-quality stills.",
             "R-S04-5",
             "The coordinating unit's ChildFind inbox remains usable on a typical search day (on the order of the national Amber rate, not a continuous firehose).",
             "Human attention is part of the environment the REQ depends on.",
             [A("R-S04-5-A1", "Thresholding will keep volume near the 1-alert/day national rate times a small match rate.", "If we lower threshold for recall, volume explodes locally."),
              A("R-S04-5-A2", "Reviewers will not rubber-stamp to clear the queue.", "They will if measured on throughput."),
              A("R-S04-5-A3", "Geographic scoping keeps a rural desk from seeing a coastal city's matches.", "A national inbox is simpler to build.")],
             [P("R-S04-5-P1", "cloud/search coordinator", "Shard the inbox by coordinating-unit geo-fence; do not show out-of-fence stills."),
              P("R-S04-5-P2", "dashcam firmware", "Cap queued candidate stills per search-id per hour and mark overflow as count-only."),
              P("R-S04-5-P3", "cloud/search coordinator", "Surface queue depth next to each case so coordinators see overload as a first-class status.")]),
            ("L-S04-6", "G-S04-1",
             "Traditional canvassing stops because 'the cameras would have seen them'.",
             "R-S04-6",
             "Investigators continue non-camera search activity even while ChildFind is active.",
             "Automation complacency is an environmental/organizational failure.",
             [A("R-S04-6-A1", "Command staff treat ChildFind as one sensor among many.", "Vendors will sell it as coverage."),
              A("R-S04-6-A2", "Coverage maps are not mistaken for 'every street is enrolled'.", "They will be."),
              A("R-S04-6-A3", "A degraded/offline status is visible in the same UI as pins.", "Separate dashboards get ignored.")],
             [P("R-S04-6-P1", "cloud/search coordinator", "Show enrolled-device density, not just pins, on the dispatch map."),
              P("R-S04-6-P2", "cloud/search coordinator", "If ack coverage is below a floor, banner 'camera network not a substitute for canvass'."),
              P("R-S04-6-P3", "phone companion app", "Report last-seen GPS only when the device was actually matching, not when it was powered off.")]),
        ],
    )

    add(
        "S05",
        ["mission success", "public trust", "volunteer sustainability"],
        [G("G-S05-1", "Increase recoveries without becoming a surveillance brand"),
         G("G-S05-2", "Keep volunteers and donors engaged")],
        [
            ("L-S05-1", "G-S05-1",
             "A privacy scandal ends the partnership and the search capability with it.",
             "R-S05-1",
             "Bystanders and families do not experience a ChildFind privacy incident that becomes public during the partnership.",
             "Trust is the non-profit's actual capital.",
             [A("R-S05-1-A1", "The manufacturer will not ship a 'growth' feature that fans photos to drivers.", "Marketing alignment is not guaranteed."),
              A("R-S05-1-A2", "Edge partners will not advertise 'we help find kids' with customer CCTV stills.", "They will want the PR."),
              A("R-S05-1-A3", "A single incident will be contained by contracts.", "Screenshots travel faster than contracts.")],
             [P("R-S05-1-P1", "cloud/search coordinator", "Bind photo display to reviewer and dispatch roles; no public CDN URLs for stills."),
              P("R-S05-1-P2", "cloud/search coordinator", "Require the non-profit compliance role to sign off on any new output surface (driver UI, kiosk screen, parent map)."),
              P("R-S05-1-P3", "edge kiosk", "Do not show search photos or match stills on a customer-facing screen.")]),
            ("L-S05-2", "G-S05-2",
             "Donors leave after a high-profile miss that is blamed on the non-profit 'using AI'.",
             "R-S05-2",
             "The public description of a miss does not claim that cameras covered a place they did not.",
             "Overclaiming coverage is how AI partnerships die.",
             [A("R-S05-2-A1", "Press statements will be coordinated with coverage facts.", "Speed of news vs slowness of logs."),
              A("R-S05-2-A2", "The manufacturer will not claim 'citywide' in ads.", "They might."),
              A("R-S05-2-A3", "Families will not be used as ad testimonials while a search is open.", "Growth teams will ask.")],
             [P("R-S05-2-P1", "cloud/search coordinator", "Export a coverage-fact sheet per case (ack counts, fences, outages) to the non-profit comms role."),
              P("R-S05-2-P2", "cloud/search coordinator", "Block in-product prompts that ask families for testimonials until case-closed."),
              P("R-S05-2-P3", "phone companion app", "Consumer marketing copy in-app must pull the same coverage numbers rather than a static slogan.")]),
            ("L-S05-3", "G-S05-2",
             "Volunteer reviewers quit because the queue is mostly not-the-child stills.",
             "R-S05-3",
             "Volunteer review load stays within a published per-search budget the non-profit accepted.",
             "Human review is a mitigation for model errors; it can become the new hazard.",
             [A("R-S05-3-A1", "Volunteers are interchangeable and always available.", "They are not."),
              A("R-S05-3-A2", "Top-k stills are a small number.", "k grows when recall panic hits."),
              A("R-S05-3-A3", "Reviewing children's faces all day is psychologically tolerable.", "It may not be.")],
             [P("R-S05-3-P1", "cloud/search coordinator", "Enforce a per-search cap on stills sent to volunteers; overflow goes to a paid on-call role."),
              P("R-S05-3-P2", "cloud/search coordinator", "Show estimated remaining queue time to the volunteer before they accept a shift."),
              P("R-S05-3-P3", "cloud/search coordinator", "Provide a skip/escalate control so a volunteer can drop a still without it disappearing.")]),
            ("L-S05-4", "G-S05-1",
             "The company uses the non-profit's name to sell dashcams, then ships a weaker privacy mode than the partnership described.",
             "R-S05-4",
             "Devices advertised under the partnership actually run the same matching and retention rules the non-profit signed.",
             "SKU fragmentation is how ethics agreements die.",
             [A("R-S05-4-A1", "One firmware train serves OEM and consumer SKUs.", "Low-end SKUs will strip 'expensive' deletion and ack features."),
              A("R-S05-4-A2", "The non-profit can audit production configs.", "Unless the contract is logo-only."),
              A("R-S05-4-A3", "Owners cannot disable deletion while leaving matching on.", "A 'privacy off / matching on' toggle will be requested.")],
             [P("R-S05-4-P1", "dashcam firmware", "Refuse to enable matching unless retention-limit and ack features are compiled in and healthy."),
              P("R-S05-4-P2", "cloud/search coordinator", "Expose a config-attestation hash per device that the non-profit can sample."),
              P("R-S05-4-P3", "phone companion app", "Do not offer a matching-on / deletion-off combination.")]),
            ("L-S05-5", "G-S05-1",
             "Search photos of children circulate in volunteer Slack, press, or the contractor's demo reel.",
             "R-S05-5",
             "A child's search photo is not available to people outside the authorized search roles.",
             "Distribution, not collection, is where most leaks happen.",
             [A("R-S05-5-A1", "Reviewer tools block download and external share.", "People use phones to photograph monitors."),
              A("R-S05-5-A2", "The contractor's sales team cannot pull production examples.", "They will ask for 'realistic' demos."),
              A("R-S05-5-A3", "Expired searches vanish from every replica, including backups, within a stated window.", "Backups lag.")],
             [P("R-S05-5-P1", "cloud/search coordinator", "Issue short-lived, watermarked, non-downloadable still URLs bound to reviewer identity."),
              P("R-S05-5-P2", "person-recognition contractor", "Production photos are not readable by the vendor's sales or research roles."),
              P("R-S05-5-P3", "cloud/search coordinator", "On expiry, delete photos from object storage and enqueue backup-tombstones.")]),
        ],
    )

    add(
        "S06",
        ["brand safety", "vehicle safety regulation", "warranty cost"],
        [G("G-S06-1", "Offer ChildFind as a differentiator without creating a recall"),
         G("G-S06-2", "Not be seen as shipping a mass-surveillance car")],
        [
            ("L-S06-1", "G-S06-1",
             "A crash is attributed to a ChildFind prompt or to compute starving the vehicle electrical system.",
             "R-S06-1",
             "ChildFind does not present driving-relevant alerts to the driver and does not take the vehicle electrical system below the OEM's reserved budget.",
             "NHTSA will not care that the ML model was accurate.",
             [A("R-S06-1-A1", "The dashcam is on an accessory circuit the OEM sized for it.", "Aftermarket installs share cigarette-lighter circuits with other loads."),
              A("R-S06-1-A2", "Infotainment will not be used as the match UI.", "It is the tempting place to put a big picture."),
              A("R-S06-1-A3", "Parking-mode current draw stays within the OEM spec.", "Always-on matching will not.")],
             [P("R-S06-1-P1", "dashcam firmware", "Honor an OEM current-budget sample; shed matching before crash-loop recording."),
              P("R-S06-1-P2", "dashcam firmware", "No video output of match crops onto infotainment while gear is not Park."),
              P("R-S06-1-P3", "phone companion app", "No driver-facing match UI while speed > 0, as in R-S01-3.")]),
            ("L-S06-2", "G-S06-2",
             "Press describes the car as a rolling face-recognition network; OEM cancels the SKU.",
             "R-S06-2",
             "Uninvolved people photographed by the car are not identified by name or persistent id as part of ChildFind.",
             "OEM brand risk is mostly about bystanders, not about missing children.",
             [A("R-S06-2-A1", "Matching runs only while a search-id is active in the car's region.", "A 'pre-index everyone for speed' optimization will be proposed."),
              A("R-S06-2-A2", "No gallery of embeddings is kept between searches.", "On-device galleries make matching cheaper."),
              A("R-S06-2-A3", "License-plate plus face fusion will not be added as a 'bonus'.", "It will be asked for.")],
             [P("R-S06-2-P1", "dashcam firmware", "Do not persist person embeddings across search-ids; wipe on expiry."),
              P("R-S06-2-P2", "person-recognition model", "Do not output a name or identity other than match_score vs the current search photo."),
              P("R-S06-2-P3", "dashcam firmware", "Do not run plate recognition as part of the ChildFind path unless a separate, authorized field is present in the search-alert.")]),
            ("L-S06-3", "G-S06-1",
             "Warranty returns spike because ChildFind overheats or bricks low-end units.",
             "R-S06-3",
             "Low-end hardware either performs matching within thermal limits or reports itself as non-participating rather than failing.",
             "Heterogeneous compute is in the scenario.",
             [A("R-S06-3-A1", "A single model will run on every SKU.", "It will not."),
              A("R-S06-3-A2", "Thermal throttling still leaves crash recording intact.", "Not if the SoC is shared."),
              A("R-S06-3-A3", "Owners accept that some SKUs only upload clips to the phone for matching.", "They must be told.")],
             [P("R-S06-3-P1", "dashcam firmware", "If temperature or utilization exceeds a SKU-specific limit, stop matching and emit search-degraded."),
              P("R-S06-3-P2", "phone companion app", "Offer on-phone matching as a fallback only when the user has accepted the data/compute cost."),
              P("R-S06-3-P3", "cloud/search coordinator", "Treat search-degraded devices as uncovered in the density map.")]),
            ("L-S06-4", "G-S06-1",
             "A regulator treats always-on interior/cabin matching as illegal surveillance in the car.",
             "R-S06-4",
             "Cabin-facing cameras, if present, are not used to match passengers for ChildFind.",
             "Many 'dashcams' are dual-channel.",
             [A("R-S06-4-A1", "ChildFind uses only the outward road camera.", "A cabin cam would 'help' with kidnapped-in-car cases."),
              A("R-S06-4-A2", "Passengers consented because they sat down.", "They did not."),
              A("R-S06-4-A3", "OEM privacy mode already disables the cabin cam.", "Owners re-enable it for driver monitoring.")],
             [P("R-S06-4-P1", "dashcam firmware", "Bind the ChildFind matcher input to the outward camera device id only."),
              P("R-S06-4-P2", "dashcam firmware", "Refuse search-alert processing if the configured source is a cabin device."),
              P("R-S06-4-P3", "phone companion app", "Show which camera is enrolled; no toggle to include cabin for ChildFind.")]),
            ("L-S06-5", "G-S06-2",
             "Dealers cannot explain the feature, so they disable it, leaving advertised coverage fictional.",
             "R-S06-5",
             "A car advertised as ChildFind-capable is actually enrolled or is labeled at sale as not enrolled.",
             "Channel fiction shows up as empty density maps.",
             [A("R-S06-5-A1", "Enrollment happens at delivery with a real owner account.", "It will be skipped."),
              A("R-S06-5-A2", "A factory default of 'on' is acceptable.", "Privacy law and the owner may disagree."),
              A("R-S06-5-A3", "Dealers will not promise coverage the car does not have.", "They will.")],
             [P("R-S06-5-P1", "phone companion app", "Enrollment requires an explicit owner action after delivery; factory default is matching-off."),
              P("R-S06-5-P2", "cloud/search coordinator", "OEM inventory APIs must not mark a VIN as covering a fence until a device ack exists."),
              P("R-S06-5-P3", "cloud/search coordinator", "Provide a dealer-safe status: not-enrolled vs enrolled, with no search photos.")]),
        ],
    )

    return analyses, decomps


def seed() -> None:
    # Imported here to keep module import light if someone only needs STAKEHOLDERS.
    from .seed_part2 import analyses_part2, decomps_part2

    part1_a, part1_d = _analysis_bundle()
    part2_a, part2_d = remaining_stakeholders()
    extra_a, extra_d = analyses_part2(), decomps_part2()
    analyses = part1_a + part2_a + extra_a
    decomps = part1_d + part2_d + extra_d

    io_util.write_json("stakeholders.json", {
        "approved": True,
        "instructions": "Human-reviewed list used for the submitted report.",
        "system": "ChildFind Dashcam Search",
        "stakeholders": STAKEHOLDERS,
    })
    io_util.write_json("hazards.json", {
        "approved": True,
        "instructions": "Human-reviewed losses/REQs. Wording tightened to world-level REQs.",
        "analyses": analyses,
    })
    io_util.write_json("requirements.json", {
        "approved": True,
        "instructions": "Human-reviewed ASM/SPEC. SPEC is interface-only; ASM is world/shared.",
        "decompositions": decomps,
    })
    n_loss = sum(len(a["items"]) for a in analyses)
    io_util.write_json("priorities.json", {
        "approved": True,
        "instructions": (
            "Candidate ranking only. The four items in key_results.md were chosen by a human "
            "and are not automatically the top four of this list."
        ),
        "ranking": [
            {"req_id": "R-S02-1", "severity": 5, "plausibility": 5, "easy_to_miss": 5, "surprising": True,
             "rationale": "Mission REQ; dies on connectivity even if the model is perfect."},
            {"req_id": "R-S09-1", "severity": 5, "plausibility": 4, "easy_to_miss": 5, "surprising": True,
             "rationale": "Recall-first design causes police contact with the wrong child."},
            {"req_id": "R-S08-1", "severity": 4, "plausibility": 5, "easy_to_miss": 5, "surprising": True,
             "rationale": "One-to-one matching still builds a biometric pipeline over bystanders."},
            {"req_id": "R-S01-6", "severity": 4, "plausibility": 4, "easy_to_miss": 5, "surprising": True,
             "rationale": "Unsettled authorization turns search-ids into a location oracle."},
            {"req_id": "R-S02-5", "severity": 5, "plausibility": 5, "easy_to_miss": 4, "surprising": True,
             "rationale": "Adult face stack is the wrong domain for missing children."},
            {"req_id": "R-S04-4", "severity": 4, "plausibility": 4, "easy_to_miss": 4, "surprising": False,
             "rationale": "Purpose creep once the camera network exists."},
            {"req_id": "R-S11-1", "severity": 3, "plausibility": 4, "easy_to_miss": 5, "surprising": True,
             "rationale": "Edge kiosks become checkpoints unless frozen as offload-only."},
            {"req_id": "R-S01-3", "severity": 5, "plausibility": 3, "easy_to_miss": 3, "surprising": False,
             "rationale": "Driver prompts are an OEM-killer; easier to notice than connectivity."},
        ],
    })
    print(f"Seeded {len(STAKEHOLDERS)} stakeholders, {n_loss} losses/REQs, {len(decomps)} decompositions.")
    render_report()


if __name__ == "__main__":
    io_util.ensure_workspace()
    seed()
